### ISSUE TITLE
Add a "write out all iobroker scripts into files/sync once" function

### ISSUE THREAD

**Issue by Apollon77** [soef/iobroker.js2fs#10]
i had experiences issue #9 and so my file storage and my scripts in iobroker went out of sync. In this case I saw it very soon, but only because i looked in the logs ... so in this case I know which scriptfile I need to "resync" after the adapter got fixed ... but when not then a function like the "hm-rpc" "sync once on next adapter start" would be great. 

This should simply overwrite all files with the status/content from iobroker. New local files can be added to iobroker too ...

**Comment by Apollon77** [comment]
really "$" in pathname ?! :-) why not appending ".backup" to root dir or so ?!

**Comment by Apollon77** [comment]
see also commit comment here https://github.com/soef/iobroker.js2fs/commit/285dbd3167215ff32ccaf47c29b6fd307a65afa1#diff-8b455fed45511b46d0b814c33f0aded6R776

**Comment by soef** [comment]
I've used a $ to not conflict with existing directories. But I can also use fs2js-backup.

**Comment by Apollon77** [comment]
Thank you! It's always hard to work with directory names with special chars in on shell :-)
