### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [soef/iobroker.js2fs#29]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/soef/iobroker.js2fs

- [ ] [E003] Repository must have name ioBroker.adaptername, but now io"b"roker is in lowercase
- [ ] [E004] No adapter name found in URL: https://raw.githubusercontent.com/soef/iobroker.js2fs/master
- [ ] [E020] Name of adapter in package.json must be lowercase and be equal to "iobroker.". Now is "undefined"
- [ ] [E103] common.name in io-package.json must be equal to "". Now is js2fs
- [ ] [E104] No common.titleLang found in io-package.json
- [ ] [E109] desc in io-package.json should be an object for many languages. Found only Javascript to file
- [ ] [E114] No adapter are allowed in the repo without admin3 support
- [ ] [E115] No license found in io-package.json
- [ ] [E130] Too many news found in io-package.json. Mast be less than 21. Please remove old news.
- [ ] [E150] No common.connectionType found in io-package.json
- [ ] [E152] No common.dataSource found in io-package.json
- [ ] [E200] Not found on npm. Please publish
- [ ] [E506] More non translated in german or russian words found in admin/words.js. You can use https://translator.iobroker.in/ for translations
- [ ] [E802] No topics found in the repository. Please go to "https://github.com/soef/iobroker.js2fs", press the settings button beside the about title and add some topics.
- [ ] [E603] NO "## Changelog" found in README.md
- [ ] [E604] No "## License" found in README.md
- [ ] [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 soef <soef@gmx.net>" at the start of LICENSE

I have also found warnings that may be fixed if possible.

- [ ] [W113] Adapter should support compact mode
- [ ] [W400] Cannot find "" in latest repository
- [ ] [W505] setTimeout found in "js2fs.js", but no clearTimeout detected

Thanks,
your automatic adapter checker.

P.S.: There is a community in Github, which supports the maintenance and further development of adapters. There you will find many experienced developers who are always ready to assist anyone. New developers are always welcome there. For more informations visit: https://github.com/iobroker-community-adapters/info

**Comment by jogibear9988** [comment]
This issue was moved to iobroker-community-adapters/ioBroker.js2fs-community#9

**Comment by ioBrokerChecker** [comment]
Do you need help fixing the bugs?

**Comment by ioBrokerChecker** [comment]
Thanks, that all bugs have been fixed.
