### ISSUE TITLE
Double scan on new created objects on hd

### ISSUE THREAD

**Issue by Apollon77** [soef/iobroker.js2fs#6]
see https://travis-ci.org/Apollon77/iobroker.js2fs/jobs/269536488#L1368 till L1391

and my comment here:
https://github.com/soef/iobroker.js2fs/commit/086ed199c6cb48eed1eef2bccef17bdc7be9ab18#diff-8b455fed45511b46d0b814c33f0aded6L358

**Comment by soef** [comment]
You are right, it is read twice. - Normally, an object change by js2fs should not be handled in the onObjectChange. But in this case, this fits quite well, since onObjectChange is left directly with a restart. Thank you.

**Comment by Apollon77** [comment]
took me some time to find out as I was doing the changes :-)
