### ISSUE TITLE
Exception (source not defined) when updating script inside iobroker

### ISSUE THREAD

**Issue by Apollon77** [soef/iobroker.js2fs#9]
hey,

I changed a script in iobroker and klicked on "save".
Then the following exception happened:

js2fs.0 | 2017-08-31 08:26:10.153 | info | terminating
-- | -- | -- | --
js2fs.0 | 2017-08-31 08:26:10.142 | error | at Timer.listOnTimeout (timers.js:214:5)
js2fs.0 | 2017-08-31 08:26:10.142 | error | at tryOnTimeout (timers.js:250:5)
js2fs.0 | 2017-08-31 08:26:10.142 | error | at ontimeout (timers.js:386:14)
js2fs.0 | 2017-08-31 08:26:10.142 | error | at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:808:81)
js2fs.0 | 2017-08-31 08:26:10.142 | error | at Object.options.objectChange (/opt/iobroker/node_modules/iobroker.js2fs/node_modules/soef/soef.js:1322:41)
js2fs.0 | 2017-08-31 08:26:10.142 | error | at Object.onObjectChange (/opt/iobroker/node_modules/iobroker.js2fs/js2fs.js:116:28)
js2fs.0 | 2017-08-31 08:26:10.142 | error | ReferenceError: source is not defined
js2fs.0 | 2017-08-31 08:26:10.140 | error | uncaught exception: source is not defined

**Comment by Apollon77** [comment]
I will send a fix and add tests

**Comment by Apollon77** [comment]
PS: I would support adding the adapter to the repo if you like :-) I will approve the PR

**Comment by soef** [comment]
I have added a base sync. The existing destination directory will be renamed (moved to ./$ba), new created and filld with new data from ioBroker.

Yes, you call add this Adapter to the repro.

**Comment by Apollon77** [comment]
tell me when current version (>=0.0.10) is available on npm and I will add it

**Comment by soef** [comment]
Version 0.0.11 was yesterday already on npm. Now version 0.0.12 is on npm.

**Comment by Apollon77** [comment]
Added to Repo: https://github.com/ioBroker/ioBroker.repositories/commit/13b499e804d21114a563f9ad596fa97dc09ae6c5

**Comment by soef** [comment]
Thank you :-)
